const Events = {
    LOAD_RESOURCES: 'LOAD_RESOURCES',
    RESOURCES_LOADED: 'RESOURCES_LOADED',
    SET_SCENE: 'SET_SCENE',
    ANIMATE_START: 'ANIMATE_START',
    ANIMATE_END: 'ANIMATE_END',
    POINTER_UP: 'POINTER_UP',
    RENDERER_POINTER_UP: 'RENDERER_POINTER_UP',
}

export default Events
