const EventsComponents = {
    FOLLOW_3D_SET_TARGET: 'FOLLOW_3D_SET_TARGET',
    OBJECT_3D_SET_POSITION: 'OBJECT_3D_SET_POSITION',
    OBJECT_3D_LOOK_AT: 'OBJECT_3D_LOOK_AT',
    OBJECT_3D_LOOK_AT_ANIM: 'OBJECT_3D_LOOK_AT_ANIM',
    ANIM_3D_SET_ANIM: 'ANIM_3D_SET_ANIM',
}

export default EventsComponents
